server:
  port: 8003

eureka:
  instance:
    hostname: localhost
    port: 8001
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        password: 'hayabusa1300'
        platform: mysql
        url: jdbc:mysql://localhost:3306/DB_SUPERMARKET
        username: cassio
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: create
        show-sql: true
