server:
  port: 8003

eureka:
  instance:
    hostname: localhost
    port: 8001
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        driver-class-name: org.h2.Driver  
        password: ''
        platform: mysql
        url: jdbc:h2:mem:DB_SUPERMARKET
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: update
        show-sql: true


